# Generated by Django 5.1.1 on 2024-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecureData',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('md5_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
