# Generated by Django 5.1.1 on 2024-10-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
